### ISSUE TITLE
/lang/ path causes 404 not found error

### ISSUE THREAD

**Issue by konieckropka** [PhraseApp-Blog/javascript-l10n-ultimate-guide#4]
In https://github.com/PhraseApp-Blog/javascript-l10n-ultimate-guide/blob/main/vanilla/js/scripts.js
infetch async function 

```
// Retrieves translations JSON object for the given
// locale over the network
async function fetchTranslationsFor(newLocale) {
  const response = await fetch(`/lang/${newLocale}.json`);
  return await response.json();
}
```

you should change path
**/lang/**

to relative path:
**./lang/**

![image](https://user-images.githubusercontent.com/2354823/164289010-833edd8b-a808-4931-b225-8ca078b4c6c5.png)

![image](https://user-images.githubusercontent.com/2354823/164289340-19690500-b763-4ab4-ace1-9d5f4acf9daf.png)

**Comment by ashour** [comment]
Hey @konieckropka, I hope you're well. I think this issue happens when you attempt to serve the app from the repo's root folder rather then the /vanilla subfolder. This is mentioned in the README:

1. Ensure that you have [Node](https://nodejs.org/en/)
   installed on your dev machine
1. Navigate to `<project_root>/vanilla`
1. Run `npx serve` from the command line

I just followed the above and everything seems to be working fine.
